# Generated by Django 4.1.3 on 2022-12-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="상품명")),
                ("price", models.IntegerField(verbose_name="상품가격")),
                ("descrtiption", models.TextField(verbose_name="상품설명")),
                ("stuck", models.IntegerField(verbose_name="재고")),
                (
                    "registered_dttm",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록날짜"),
                ),
            ],
            options={
                "verbose_name": "제품",
                "verbose_name_plural": "제품",
                "db_table": "lifang_django_product",
            },
        ),
    ]
