# Generated by Django 4.1.3 on 2022-12-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="stuck",
            new_name="stock",
        ),
    ]
