# Generated by Django 4.1.5 on 2023-01-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_rename_stuck_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=80, verbose_name="상품명1"),
        ),
    ]
