# Generated by Django 4.1.5 on 2023-01-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "기업목록", "verbose_name_plural": "기업목록"},
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=80, verbose_name="기업명1"),
        ),
    ]
