# Generated by Django 4.1.5 on 2023-01-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_product_options_alter_product_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "제품", "verbose_name_plural": "제품"},
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=80, verbose_name="상품명1"),
        ),
    ]
