# Generated by Django 4.1.5 on 2023-01-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_product_options_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=256, verbose_name="상품명"),
        ),
    ]
