# Generated by Django 4.1.5 on 2023-01-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_product_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "기업명", "verbose_name_plural": "기업명"},
        ),
        migrations.AddField(
            model_name="product",
            name="brandcompany",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="브랜드명"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="namecompany",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="기업명"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="projectcompany",
            field=models.CharField(
                default="", max_length=256, null=True, verbose_name="프로젝트명"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=256, verbose_name="상품명1"),
        ),
    ]
