# Generated by Django 4.1.3 on 2022-12-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifanguser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lifanguser",
            name="level",
            field=models.CharField(
                choices=[("admin", "admin"), ("user", "user")],
                default="user",
                max_length=8,
                verbose_name="등급",
            ),
            preserve_default=False,
        ),
    ]
