# Generated by Django 4.1.4 on 2022-12-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifanguser", "0002_lifanguser_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lifanguser",
            name="level",
            field=models.CharField(
                choices=[("admin", "admin"), ("user", "user")],
                max_length=64,
                verbose_name="등급",
            ),
        ),
        migrations.AlterField(
            model_name="lifanguser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="비밀번호"),
        ),
    ]
