# Generated by Django 4.1.4 on 2022-12-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifanguser", "0003_alter_lifanguser_level_alter_lifanguser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lifanguser",
            name="level",
            field=models.CharField(
                choices=[("user", "user"), ("admin", "admin")],
                max_length=64,
                verbose_name="등급",
            ),
        ),
    ]
