# Generated by Django 4.1.5 on 2023-01-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifanguser", "0011_alter_lifanguser_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lifanguser",
            name="level",
            field=models.CharField(
                choices=[("user", "user"), ("admin", "admin")],
                max_length=64,
                verbose_name="등급",
            ),
        ),
    ]
