# Generated by Django 4.1.3 on 2022-12-06 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("lifanguser", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="수량")),
                (
                    "registered_dttm",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록날짜"),
                ),
                (
                    "lifanguser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lifanguser.lifanguser",
                        verbose_name="사용자",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "주문",
                "verbose_name_plural": "주문",
                "db_table": "lifang_django_order",
            },
        ),
    ]
