# Generated by Django 4.1.4 on 2022-12-22 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_memo_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="memo",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
    ]
