# Generated by Django 4.1.4 on 2022-12-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_remove_order_memo_remove_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="memo",
            field=models.TextField(blank=True, null=True, verbose_name="메모"),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="대기중", max_length=32, verbose_name="상태"),
        ),
    ]
